In [2]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st

# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

# Import API key
g_key="AIzaSyBw2oaXwfKc8PDY8slvtki6QHLAJDIZvm0"

# Study data files
yelp_path = "data/Final_Yelp_Data.csv"

# Read the mouse data and the study results
yelpers = pd.read_csv(yelp_path)

FileNotFoundError: [Errno 2] File data/Final_Yelp_Data.csv does not exist: 'data/Final_Yelp_Data.csv'

In [ ]:
yelpers.head()

In [5]:
#compare each type of food and review count
# grab categories, name, review count, and rating
df = pd.DataFrame(yelpers, columns = ['name', 'categories', 'review_count', 'rating', 'transactions', 'coordinates']) 

df.head()

,name,categories,review_count,rating,transactions,coordinates
0,Junoon Flavors Of India,"[{'alias': 'indpak', 'title': 'Indian'}]",20,5.0,[],"{'latitude': 38.570471, 'longitude': -121.4571..."
1,Shake Shack,"[{'alias': 'burgers', 'title': 'Burgers'}, {'a...",168,3.0,['delivery'],"{'latitude': 38.568686, 'longitude': -121.487243}"
2,South,"[{'alias': 'southern', 'title': 'Southern'}]",1590,4.0,['delivery'],"{'latitude': 38.5687015705627, 'longitude': -1..."
3,Fixins Soul Kitchen,"[{'alias': 'soulfood', 'title': 'Soul Food'}, ...",946,4.5,['delivery'],"{'latitude': 38.55147, 'longitude': -121.46924}"
4,Chando’s Tacos,"[{'alias': 'mexican', 'title': 'Mexican'}]",14,4.5,[],"{'latitude': 38.564075, 'longitude': -121.4340..."

In [31]:
#geomap the restaurants with most reviews
#top 20 and low 20
#df = pd.DataFrame(df.row.str.split(' ',1).tolist(),
#                                 columns = ['coordinates'])
df['lat'], df['long'] = df['coordinates'].str.split(',', 1).str
df['lat']= df['lat'].str.replace("{'latitude':", "")
df['long'] = df['long'].str.replace("'longitude': ", "").str.replace("}", "")
df
df[['long', 'lat']]= df[['long', 'lat']].astype(float, errors= "ignore")
#df['long'].isna().sum()
df

/Users/fatimadonato/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: FutureWarning: Columnar iteration over characters will be deprecated in future releases.
  """

,name,categories,review_count,rating,transactions,coordinates,lat,long
0,Junoon Flavors Of India,"[{'alias': 'indpak', 'title': 'Indian'}]",20,5.0,[],"{'latitude': 38.570471, 'longitude': -121.4571...",38.570471,-121.4571694
1,Shake Shack,"[{'alias': 'burgers', 'title': 'Burgers'}, {'a...",168,3.0,['delivery'],"{'latitude': 38.568686, 'longitude': -121.487243}",38.568686,-121.487243
2,South,"[{'alias': 'southern', 'title': 'Southern'}]",1590,4.0,['delivery'],"{'latitude': 38.5687015705627, 'longitude': -1...",38.5687015705627,-121.497104891816
3,Fixins Soul Kitchen,"[{'alias': 'soulfood', 'title': 'Soul Food'}, ...",946,4.5,['delivery'],"{'latitude': 38.55147, 'longitude': -121.46924}",38.55147,-121.46924
4,Chando’s Tacos,"[{'alias': 'mexican', 'title': 'Mexican'}]",14,4.5,[],"{'latitude': 38.564075, 'longitude': -121.4340...",38.564075,-121.43409833
...,...,...,...,...,...,...,...,...
709,Smoke Junction Cafe,"[{'alias': 'bbq', 'title': 'Barbeque'}, {'alia...",32,4.0,['delivery'],"{'latitude': 38.7050490891277, 'longitude': -1...",38.7050490891277,-121.328696432458
710,Tealicious,"[{'alias': 'bubbletea', 'title': 'Bubble Tea'}...",169,4.0,['pickup'],"{'latitude': 38.5275870192814, 'longitude': -1...",38.5275870192814,-121.495912777778
711,Three Sisters Mexican Restaurant,"[{'alias': 'mexican', 'title': 'Mexican'}, {'a...",403,3.0,"['pickup', 'delivery']","{'latitude': 38.56015, 'longitude': -121.4435}",38.56015,-121.4435
712,Honey Baked Ham Company,"[{'alias': 'meats', 'title': 'Meat Shops'}, {'...",66,3.5,"['pickup', 'delivery']","{'latitude': 38.6623840332031, 'longitude': -1...",38.6623840332031,-121.271705627441
713,Sourdough & Co.,"[{'alias': 'salad', 'title': 'Salad'}, {'alias...",116,3.5,['delivery'],"{'latitude': 38.664591, 'longitude': -121.272799}",38.664591,-121.272799

In [50]:
df= df.sort_values("review_count", ascending= False)
top20= df.head(20)
top20[['long', 'lat']]= top20[['long', 'lat']].astype(float)

/Users/fatimadonato/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:2963: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

In [57]:
df= df.sort_values("review_count", ascending= False)
tail= df[df["review_count"]==1]
tail[['long', 'lat']]= tail[['long', 'lat']].astype(float)
tail= tail[tail['long'] <-120]
tail

/Users/fatimadonato/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:2963: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

,name,categories,review_count,rating,transactions,coordinates,lat,long
451,Burger King,"[{'alias': 'hotdogs', 'title': 'Fast Food'}, {...",1,4.0,[],"{'latitude': 38.6665820275127, 'longitude': -1...",38.666582,-121.388769
146,Baker Dozen 2,"[{'alias': 'restaurants', 'title': 'Restaurant...",1,3.0,[],"{'latitude': 38.75193, 'longitude': -121.28109}",38.751930,-121.281090
305,TACOS GTO,"[{'alias': 'foodtrucks', 'title': 'Food Trucks...",1,5.0,[],"{'latitude': 38.6451, 'longitude': -121.44154}",38.645100,-121.441540
482,Las Cachanillas Restaurant,"[{'alias': 'mexican', 'title': 'Mexican'}, {'a...",1,4.0,['delivery'],"{'latitude': 38.60733833, 'longitude': -121.47...",38.607338,-121.476527
506,Mango’s Burger Bar,"[{'alias': 'salad', 'title': 'Salad'}, {'alias...",1,4.0,[],"{'latitude': 38.575439, 'longitude': -121.480671}",38.575439,-121.480671
494,Young Dong,"[{'alias': 'korean', 'title': 'Korean'}]",1,1.0,['delivery'],"{'latitude': 38.52425, 'longitude': -121.4971651}",38.524250,-121.497165
313,Five-Twenty Four Restaurant,"[{'alias': 'restaurants', 'title': 'Restaurant...",1,2.0,[],"{'latitude': 38.6097235232592, 'longitude': -1...",38.609724,-121.475631
213,El Zacatecano,"[{'alias': 'newamerican', 'title': 'American (...",1,5.0,[],"{'latitude': 38.5069695, 'longitude': -121.470...",38.506969,-121.470070
246,Larosa's Sports Cafe,"[{'alias': 'restaurants', 'title': 'Restaurant...",1,1.0,[],"{'latitude': 38.6421467, 'longitude': -121.383...",38.642147,-121.383989
284,Chili's Catering,"[{'alias': 'bars', 'title': 'Bars'}, {'alias':...",1,5.0,[],"{'latitude': 38.66264, 'longitude': -121.27263}",38.662640,-121.272630
65,Outdoor Herbivore,"[{'alias': 'diyfood', 'title': 'Do-It-Yourself...",1,5.0,[],"{'latitude': 38.6095010505836, 'longitude': -1...",38.609501,-121.367493
460,Cafe 26,"[{'alias': 'coffee', 'title': 'Coffee & Tea'},...",1,4.0,[],"{'latitude': 38.74887, 'longitude': -121.26598}",38.748870,-121.265980
262,Sun Center Cafe,"[{'alias': 'cafes', 'title': 'Cafes'}]",1,5.0,[],"{'latitude': 38.554607, 'longitude': -121.373375}",38.554607,-121.373375
50,Playa Linda Del Carmen,"[{'alias': 'latin', 'title': 'Latin American'}]",1,5.0,[],"{'latitude': 38.690579, 'longitude': -121.4565...",38.690579,-121.456554
480,Café Hoshi,"[{'alias': 'cafes', 'title': 'Cafes'}]",1,5.0,[],"{'latitude': 38.5782404, 'longitude': -121.487...",38.578240,-121.487862
267,Fair Oaks Pizzeria,"[{'alias': 'restaurants', 'title': 'Restaurant...",1,1.0,[],"{'latitude': 38.639, 'longitude': -121.27424}",38.639000,-121.274240
162,Hall of Fame Bar & Grill,"[{'alias': 'newamerican', 'title': 'American (...",1,3.0,['delivery'],"{'latitude': 38.7098999, 'longitude': -121.291...",38.709900,-121.291313
205,La Croissant Park Cafe,"[{'alias': 'restaurants', 'title': 'Restaurant...",1,5.0,[],"{'latitude': 38.5650634765625, 'longitude': -1...",38.565063,-121.408081
175,Leonardi's Pizza,"[{'alias': 'pizza', 'title': 'Pizza'}]",1,5.0,[],"{'latitude': 38.741153717041, 'longitude': -12...",38.741154,-121.249260
411,Riego Road Strawberry Stand,"[{'alias': 'markets', 'title': 'Fruits & Veggi...",1,5.0,[],"{'latitude': 38.71598, 'longitude': -121.41362}",38.715980,-121.413620
405,Culinary Café,"[{'alias': 'cafes', 'title': 'Cafes'}]",1,5.0,[],"{'latitude': 38.602794, 'longitude': -121.418647}",38.602794,-121.418647
252,Classic Burgers,"[{'alias': 'restaurants', 'title': 'Restaurant...",1,1.0,[],"{'latitude': 38.6098899841309, 'longitude': -1...",38.609890,-121.400833
535,La Boheme Cafe,"[{'alias': 'restaurants', 'title': 'Restaurant...",1,4.0,[],"{'latitude': 38.57936, 'longitude': -121.49357}",38.579360,-121.493570
238,3- N -1 BBQ,"[{'alias': 'bbq', 'title': 'Barbeque'}]",1,5.0,[],"{'latitude': 38.6270105, 'longitude': -121.445...",38.627010,-121.445811
468,Bacchanal Bistro & Wine Bar,"[{'alias': 'pizza', 'title': 'Pizza'}]",1,5.0,[],"{'latitude': 38.74375, 'longitude': -121.25349}",38.743750,-121.253490
507,Virga's Restaurant Bar & Catering,"[{'alias': 'restaurants', 'title': 'Restaurant...",1,4.0,[],"{'latitude': 38.5730133056641, 'longitude': -1...",38.573013,-121.490189

In [58]:
gmaps.configure(api_key=g_key)

In [59]:
# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>name</dt><dd>{name}</dd>
<dt>lat</dt><dd>{lat}</dd>
<dt>long</dt><dd>{long}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
yelptop = [info_box_template.format(**row) for index, row in top20.iterrows()]
locations = top20[["lat", "long"]]
# use above variables for layer[]
#markers= gmaps.marker_layer(locations, hotel_info) #info_box_template)
fig = gmaps.figure()

markers= gmaps.marker_layer(locations, info_box_content=yelptop)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))

In [60]:
yelptail = [info_box_template.format(**row) for index, row in tail.iterrows()]
locations = tail[["lat", "long"]]
# use above variables for layer[]
#markers= gmaps.marker_layer(locations, hotel_info) #info_box_template)
fig = gmaps.figure()

markers= gmaps.marker_layer(locations, info_box_content=yelptail)
fig.add_layer(markers)
fig

Figure(layout=FigureLayout(height='420px'))